apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lcar605fc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lcar605fc-python 
  name: lcar605fc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lcar605fc-python 
